# Generated by Django 5.0.6 on 2024-05-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangochain_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.TextField()),
                ('to_id', models.TextField()),
                ('tr_id', models.TextField()),
                ('amount', models.FloatField()),
                ('signature', models.TextField()),
            ],
        ),
    ]
